name: BlockShuffle
version: 1.3
author: Viktoracri (Viktor Myrland)
main: dev.acri.blockshuffle.BlockShuffle
api-version: 1.13

commands:
  blockshuffle:
    description: The main command for the BlockShuffle plugin.
    aliases: [bs]